# syntax=docker/dockerfile:1
FROM php:8.2-fpm

RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"
COPY ./docker/php-custom.ini-development $PHP_INI_DIR/conf.d/php-custom.ini

# Set working directory
WORKDIR /var/www/html   

# Install dependencies
RUN apt-get update && \
    apt-get install -y \
        zip \
        unzip \
        git \
        libzip-dev \
        libpng-dev \
        libjpeg-dev \
        libfreetype6-dev

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN docker-php-ext-configure gd --with-jpeg && \
    docker-php-ext-install mysqli pdo pdo_mysql zip gd

# Copy existing application directory permissions
COPY . /var/www/html

RUN chown www-data:www-data storage

# Expose port 9000 and start php-fpm server
EXPOSE 9000

CMD ["php-fpm"]